name: secs

options:
  bundleIdPrefix: io.github.takeiteasy
  createIntermediateGroups: true
  deploymentTarget:
    macOS: "12.0"

settings:
  GCC_C_LANGUAGE_STANDARD: c11
  CLANG_WARN_DOCUMENTATION_COMMENTS: false

targets:
  secs:
    type: application
    platform: macOS
    info:
      path: Info.plist
    sources:
      - path: src/
      - path: tests/
