name: secs

options:
  bundleIdPrefix: io.github.takeiteasy
  createIntermediateGroups: true
  deploymentTarget:
    macOS: "14.0"

settings:
  GCC_C_LANGUAGE_STANDARD: c11
  CLANG_WARN_DOCUMENTATION_COMMENTS: false

targets:
  secs:
    type: tool 
    platform: macOS
    sources:
      - path: src/
      - path: tests/
